CATALOG_SEED = [
    {'category': 'frutas', 'name': 'Arándanos 1/4', 'estimated_price': 2000},
    {'category': 'frutas', 'name': 'Ciruelas', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Durazno Nectarin Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Durazno Plátano Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Frambuesas 1/4', 'estimated_price': 2000},
    {'category': 'frutas', 'name': 'Frutillas Kg', 'estimated_price': 2500},
    {'category': 'frutas', 'name': 'Mango Unidad', 'estimated_price': 2200},
    {'category': 'frutas', 'name': 'Manzanas Roja Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Manzanas Verdes Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Melón Tuna', 'estimated_price': 2500},
    {'category': 'frutas', 'name': 'Naranjas Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Paltas Kg', 'estimated_price': 4290},
    {'category': 'frutas', 'name': 'Pepino dulce Kg', 'estimated_price': 1790},
    {'category': 'frutas', 'name': 'Peras', 'estimated_price': 1790},
    {'category': 'frutas', 'name': 'Piña Unidad', 'estimated_price': 2500},
    {'category': 'frutas', 'name': 'Plátanos Kg', 'estimated_price': 1790},
    {'category': 'frutas', 'name': 'Sandía x Trozo (Precio x Kg)', 'estimated_price': 1000},
    {'category': 'frutas', 'name': 'Tunas Kg', 'estimated_price': 1490},
    {'category': 'frutas', 'name': 'Uva sin pepa', 'estimated_price': 1490},
    {'category': 'verduras', 'name': 'Ajo malla 5 unidades', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'Beterraga Paquete 5 unidades', 'estimated_price': 1300},
    {'category': 'verduras', 'name': 'Bolsa de Cazuela (Trozo de zapallo amarillo, Italiano, zanahoria, pimentón, poroto verde, choclo para 3 personasa)', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Bolsa de Porotos granados', 'estimated_price': 2000},
    {'category': 'verduras', 'name': 'Brocolí Unidad', 'estimated_price': 1600},
    {'category': 'verduras', 'name': 'Brucelas 1/4', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'Carbonada (Zapallo amarillo, italiano, zanahoria y espinaca)', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Cebolla morada Unidad', 'estimated_price': 400},
    {'category': 'verduras', 'name': 'Cebollas Nuevas Kg', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'champiñon 1/4', 'estimated_price': 2500},
    {'category': 'verduras', 'name': 'Champiñones picados', 'estimated_price': 1300},
    {'category': 'verduras', 'name': 'Chapsui de verduras', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Choclo americano Unidad', 'estimated_price': 500},
    {'category': 'verduras', 'name': 'Choclo Grande', 'estimated_price': 700},
    {'category': 'verduras', 'name': 'Coliflor Unidad', 'estimated_price': 1800},
    {'category': 'verduras', 'name': 'Dientes de dragón', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Espinacas Kg', 'estimated_price': 2400},
    {'category': 'verduras', 'name': 'Lechuga Costina', 'estimated_price': 1290},
    {'category': 'verduras', 'name': 'Lechuga Escarola Unidad', 'estimated_price': 1290},
    {'category': 'verduras', 'name': 'Lechuga Milanesa Unidad', 'estimated_price': 1290},
    {'category': 'verduras', 'name': 'Lechugas Española Unidad', 'estimated_price': 1290},
    {'category': 'verduras', 'name': 'Lechugas Marina Unidad', 'estimated_price': 1290},
    {'category': 'verduras', 'name': 'Limones Kg', 'estimated_price': 1990},
    {'category': 'verduras', 'name': 'Mata de Acelga', 'estimated_price': 1700},
    {'category': 'verduras', 'name': 'Mata de apio Unidad', 'estimated_price': 1690},
    {'category': 'verduras', 'name': 'Mongoliana (Dientes de dragon, Cebollín, Pimentón y Champiñon)', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Papas Kg', 'estimated_price': 790},
    {'category': 'verduras', 'name': 'Pepinos Unidad', 'estimated_price': 500},
    {'category': 'verduras', 'name': 'Pimentón amarillo Unidad', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'Pimentón rojo Unidad', 'estimated_price': 700},
    {'category': 'verduras', 'name': 'Pimentón verde Unidad', 'estimated_price': 600},
    {'category': 'verduras', 'name': 'Porotos Granados Kg', 'estimated_price': 1590},
    {'category': 'verduras', 'name': 'Porotos verdes Kg', 'estimated_price': 2000},
    {'category': 'verduras', 'name': 'Porotos verdes picados (bandeja con 200grs. Aprox.)', 'estimated_price': 1300},
    {'category': 'verduras', 'name': 'Repollo Unidad', 'estimated_price': 1500},
    {'category': 'verduras', 'name': 'Tomates Cherry 1/4 Kg', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'Tomates Kg', 'estimated_price': 1890},
    {'category': 'verduras', 'name': 'Zanahorias Kg', 'estimated_price': 1000},
    {'category': 'verduras', 'name': 'Zapallo Camote 1/2', 'estimated_price': 800},
    {'category': 'verduras', 'name': 'Zapallos italianos Unidad', 'estimated_price': 400},
    {'category': 'hierbas y complementos', 'name': 'Ají verde Unidad', 'estimated_price': 200},
    {'category': 'hierbas y complementos', 'name': 'Albahaca Mata', 'estimated_price': 800},
    {'category': 'hierbas y complementos', 'name': 'Cebollín 3 unidades', 'estimated_price': 790},
    {'category': 'hierbas y complementos', 'name': 'Ciboulette', 'estimated_price': 400},
    {'category': 'hierbas y complementos', 'name': 'Cilantro', 'estimated_price': 800},
    {'category': 'hierbas y complementos', 'name': 'Perejil', 'estimated_price': 700},
    {'category': 'legumbres y otros', 'name': 'Aceitunas (1/2 Kilo)', 'estimated_price': 4500},
    {'category': 'legumbres y otros', 'name': 'Alemendras Confitadas 100 grs.', 'estimated_price': 2000},
    {'category': 'legumbres y otros', 'name': 'Almendras 500grs.', 'estimated_price': 8000},
    {'category': 'legumbres y otros', 'name': 'Cebolla en escabeche 500 grs.', 'estimated_price': 2000},
    {'category': 'legumbres y otros', 'name': 'Garbanzos Kg', 'estimated_price': 3000},
    {'category': 'legumbres y otros', 'name': 'Genjibre (100 grs.)', 'estimated_price': 1300},
    {'category': 'legumbres y otros', 'name': 'Huevos de color extra (Unidad)', 'estimated_price': 300},
    {'category': 'legumbres y otros', 'name': 'Huevos de color super extra (c/u)', 'estimated_price': 350},
    {'category': 'legumbres y otros', 'name': 'Huevos Jumbo (Unidad)', 'estimated_price': 400},
    {'category': 'legumbres y otros', 'name': 'Lentejas Kg', 'estimated_price': 3500},
    {'category': 'legumbres y otros', 'name': 'Locos Cocidos (2 a 3 unidades)', 'estimated_price': 15000},
    {'category': 'legumbres y otros', 'name': 'Longanizas Ahumadas (Al vacío Kg)', 'estimated_price': 9000},
    {'category': 'legumbres y otros', 'name': 'Maní Confitado 250 grs.', 'estimated_price': 2000},
    {'category': 'legumbres y otros', 'name': 'Maní Tostado 250 grs.', 'estimated_price': 1750},
    {'category': 'legumbres y otros', 'name': 'Mermeladas 420 grs. Hermanas de Quilvo 100% caseras. 2*11.000', 'estimated_price': 6000},
    {'category': 'legumbres y otros', 'name': 'Nueces 500 grs.', 'estimated_price': 5000},
    {'category': 'legumbres y otros', 'name': 'Poroto Burro Kg', 'estimated_price': 3500},
    {'category': 'legumbres y otros', 'name': 'Poroto Payar Kg', 'estimated_price': 3500},
    {'category': 'legumbres y otros', 'name': 'Poroto Pelado Kg', 'estimated_price': 3500},
    {'category': 'legumbres y otros', 'name': 'Pulpa de Tomate 370 grs. Hermanas de Quilvo 100% caseras. 2*6000', 'estimated_price': 3200},
]
