create extension if not exists pgcrypto;

create table if not exists public.admins (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    password_salt text not null,
    password_hash text not null,
    created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.clients (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null unique,
    phone text not null,
    address text not null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    last_login_at timestamptz
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    name text not null unique,
    category text not null check (category in ('frutas', 'verduras', 'hierbas y complementos', 'legumbres y otros')),
    estimated_price integer not null check (estimated_price >= 0),
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete restrict,
    source_order_id bigint references public.orders(id) on delete set null,
    status text not null default 'pendiente' check (status in ('pendiente', 'comprado', 'cancelado')),
    admin_note text,
    estimated_total integer not null default 0 check (estimated_total >= 0),
    actual_total integer check (actual_total is null or actual_total >= 0),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    purchased_at timestamptz
);

create table if not exists public.order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null references public.orders(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete restrict,
    product_name text not null,
    quantity numeric(10, 2) not null check (quantity > 0),
    estimated_price integer not null check (estimated_price >= 0),
    estimated_total integer not null check (estimated_total >= 0),
    actual_price integer check (actual_price is null or actual_price >= 0),
    actual_total integer check (actual_total is null or actual_total >= 0),
    item_note text,
    was_missing boolean not null default false
);

create index if not exists idx_clients_email on public.clients(email);
create index if not exists idx_products_category_active on public.products(category, is_active, name);
create index if not exists idx_orders_client_created on public.orders(client_id, created_at desc);
create index if not exists idx_orders_created on public.orders(created_at desc);
create index if not exists idx_order_items_order on public.order_items(order_id);
create index if not exists idx_order_items_product on public.order_items(product_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists set_clients_updated_at on public.clients;
create trigger set_clients_updated_at
before update on public.clients
for each row
execute function public.set_updated_at();

drop trigger if exists set_products_updated_at on public.products;
create trigger set_products_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

drop trigger if exists set_orders_updated_at on public.orders;
create trigger set_orders_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

comment on table public.admins is 'Accesos de administracion usados por la app server-side.';
comment on table public.clients is 'Clientas registradas en Verduleria Isa.';
comment on table public.products is 'Catalogo semanal de productos.';
comment on table public.orders is 'Cabecera de pedidos de clientas.';
comment on table public.order_items is 'Detalle de productos solicitados en cada pedido.';

grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant all privileges on all functions in schema public to service_role;

alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant all on sequences to service_role;
alter default privileges in schema public grant all on functions to service_role;

