-- Catalogo inicial de Verduleria Isa
-- Ejecuta este archivo despues de 001_schema.sql

insert into public.products (name, category, estimated_price, is_active)
values
    ('Arándanos 1/4', 'frutas', 2000, true),
    ('Ciruelas', 'frutas', 1490, true),
    ('Durazno Nectarin Kg', 'frutas', 1490, true),
    ('Durazno Plátano Kg', 'frutas', 1490, true),
    ('Frambuesas 1/4', 'frutas', 2000, true),
    ('Frutillas Kg', 'frutas', 2500, true),
    ('Mango Unidad', 'frutas', 2200, true),
    ('Manzanas Roja Kg', 'frutas', 1490, true),
    ('Manzanas Verdes Kg', 'frutas', 1490, true),
    ('Melón Tuna', 'frutas', 2500, true),
    ('Naranjas Kg', 'frutas', 1490, true),
    ('Paltas Kg', 'frutas', 4290, true),
    ('Pepino dulce Kg', 'frutas', 1790, true),
    ('Peras', 'frutas', 1790, true),
    ('Piña Unidad', 'frutas', 2500, true),
    ('Plátanos Kg', 'frutas', 1790, true),
    ('Sandía x Trozo (Precio x Kg)', 'frutas', 1000, true),
    ('Tunas Kg', 'frutas', 1490, true),
    ('Uva sin pepa', 'frutas', 1490, true),
    ('Ajo malla 5 unidades', 'verduras', 1000, true),
    ('Beterraga Paquete 5 unidades', 'verduras', 1300, true),
    ('Bolsa de Cazuela (Trozo de zapallo amarillo, Italiano, zanahoria, pimentón, poroto verde, choclo para 3 personasa)', 'verduras', 1500, true),
    ('Bolsa de Porotos granados', 'verduras', 2000, true),
    ('Brocolí Unidad', 'verduras', 1600, true),
    ('Brucelas 1/4', 'verduras', 1000, true),
    ('Carbonada (Zapallo amarillo, italiano, zanahoria y espinaca)', 'verduras', 1500, true),
    ('Cebolla morada Unidad', 'verduras', 400, true),
    ('Cebollas Nuevas Kg', 'verduras', 1000, true),
    ('champiñon 1/4', 'verduras', 2500, true),
    ('Champiñones picados', 'verduras', 1300, true),
    ('Chapsui de verduras', 'verduras', 1500, true),
    ('Choclo americano Unidad', 'verduras', 500, true),
    ('Choclo Grande', 'verduras', 700, true),
    ('Coliflor Unidad', 'verduras', 1800, true),
    ('Dientes de dragón', 'verduras', 1500, true),
    ('Espinacas Kg', 'verduras', 2400, true),
    ('Lechuga Costina', 'verduras', 1290, true),
    ('Lechuga Escarola Unidad', 'verduras', 1290, true),
    ('Lechuga Milanesa Unidad', 'verduras', 1290, true),
    ('Lechugas Española Unidad', 'verduras', 1290, true),
    ('Lechugas Marina Unidad', 'verduras', 1290, true),
    ('Limones Kg', 'verduras', 1990, true),
    ('Mata de Acelga', 'verduras', 1700, true),
    ('Mata de apio Unidad', 'verduras', 1690, true),
    ('Mongoliana (Dientes de dragon, Cebollín, Pimentón y Champiñon)', 'verduras', 1500, true),
    ('Papas Kg', 'verduras', 790, true),
    ('Pepinos Unidad', 'verduras', 500, true),
    ('Pimentón amarillo Unidad', 'verduras', 1000, true),
    ('Pimentón rojo Unidad', 'verduras', 700, true),
    ('Pimentón verde Unidad', 'verduras', 600, true),
    ('Porotos Granados Kg', 'verduras', 1590, true),
    ('Porotos verdes Kg', 'verduras', 2000, true),
    ('Porotos verdes picados (bandeja con 200grs. Aprox.)', 'verduras', 1300, true),
    ('Repollo Unidad', 'verduras', 1500, true),
    ('Tomates Cherry 1/4 Kg', 'verduras', 1000, true),
    ('Tomates Kg', 'verduras', 1890, true),
    ('Zanahorias Kg', 'verduras', 1000, true),
    ('Zapallo Camote 1/2', 'verduras', 800, true),
    ('Zapallos italianos Unidad', 'verduras', 400, true),
    ('Ají verde Unidad', 'hierbas y complementos', 200, true),
    ('Albahaca Mata', 'hierbas y complementos', 800, true),
    ('Cebollín 3 unidades', 'hierbas y complementos', 790, true),
    ('Ciboulette', 'hierbas y complementos', 400, true),
    ('Cilantro', 'hierbas y complementos', 800, true),
    ('Perejil', 'hierbas y complementos', 700, true),
    ('Aceitunas (1/2 Kilo)', 'legumbres y otros', 4500, true),
    ('Alemendras Confitadas 100 grs.', 'legumbres y otros', 2000, true),
    ('Almendras 500grs.', 'legumbres y otros', 8000, true),
    ('Cebolla en escabeche 500 grs.', 'legumbres y otros', 2000, true),
    ('Garbanzos Kg', 'legumbres y otros', 3000, true),
    ('Genjibre (100 grs.)', 'legumbres y otros', 1300, true),
    ('Huevos de color extra (Unidad)', 'legumbres y otros', 300, true),
    ('Huevos de color super extra (c/u)', 'legumbres y otros', 350, true),
    ('Huevos Jumbo (Unidad)', 'legumbres y otros', 400, true),
    ('Lentejas Kg', 'legumbres y otros', 3500, true),
    ('Locos Cocidos (2 a 3 unidades)', 'legumbres y otros', 15000, true),
    ('Longanizas Ahumadas (Al vacío Kg)', 'legumbres y otros', 9000, true),
    ('Maní Confitado 250 grs.', 'legumbres y otros', 2000, true),
    ('Maní Tostado 250 grs.', 'legumbres y otros', 1750, true),
    ('Mermeladas 420 grs. Hermanas de Quilvo 100% caseras. 2*11.000', 'legumbres y otros', 6000, true),
    ('Nueces 500 grs.', 'legumbres y otros', 5000, true),
    ('Poroto Burro Kg', 'legumbres y otros', 3500, true),
    ('Poroto Payar Kg', 'legumbres y otros', 3500, true),
    ('Poroto Pelado Kg', 'legumbres y otros', 3500, true),
    ('Pulpa de Tomate 370 grs. Hermanas de Quilvo 100% caseras. 2*6000', 'legumbres y otros', 3200, true)
on conflict (name) do update
set category = excluded.category,
    estimated_price = excluded.estimated_price,
    is_active = true,
    updated_at = timezone('utc', now());
