-- Amplia las categorias soportadas y corrige las categorias del catalogo actual.
alter table public.products drop constraint if exists products_category_check;
alter table public.products add constraint products_category_check check (category in ('frutas', 'verduras', 'hierbas y complementos', 'legumbres y otros'));

update public.products set category = 'frutas' where name = 'Arándanos 1/4';
update public.products set category = 'frutas' where name = 'Ciruelas';
update public.products set category = 'frutas' where name = 'Durazno Nectarin Kg';
update public.products set category = 'frutas' where name = 'Durazno Plátano Kg';
update public.products set category = 'frutas' where name = 'Frambuesas 1/4';
update public.products set category = 'frutas' where name = 'Frutillas Kg';
update public.products set category = 'frutas' where name = 'Mango Unidad';
update public.products set category = 'frutas' where name = 'Manzanas Roja Kg';
update public.products set category = 'frutas' where name = 'Manzanas Verdes Kg';
update public.products set category = 'frutas' where name = 'Melón Tuna';
update public.products set category = 'frutas' where name = 'Naranjas Kg';
update public.products set category = 'frutas' where name = 'Paltas Kg';
update public.products set category = 'frutas' where name = 'Pepino dulce Kg';
update public.products set category = 'frutas' where name = 'Peras';
update public.products set category = 'frutas' where name = 'Piña Unidad';
update public.products set category = 'frutas' where name = 'Plátanos Kg';
update public.products set category = 'frutas' where name = 'Sandía x Trozo (Precio x Kg)';
update public.products set category = 'frutas' where name = 'Tunas Kg';
update public.products set category = 'frutas' where name = 'Uva sin pepa';
update public.products set category = 'verduras' where name = 'Ajo malla 5 unidades';
update public.products set category = 'verduras' where name = 'Beterraga Paquete 5 unidades';
update public.products set category = 'verduras' where name = 'Bolsa de Cazuela (Trozo de zapallo amarillo, Italiano, zanahoria, pimentón, poroto verde, choclo para 3 personasa)';
update public.products set category = 'verduras' where name = 'Bolsa de Porotos granados';
update public.products set category = 'verduras' where name = 'Brocolí Unidad';
update public.products set category = 'verduras' where name = 'Brucelas 1/4';
update public.products set category = 'verduras' where name = 'Carbonada (Zapallo amarillo, italiano, zanahoria y espinaca)';
update public.products set category = 'verduras' where name = 'Cebolla morada Unidad';
update public.products set category = 'verduras' where name = 'Cebollas Nuevas Kg';
update public.products set category = 'verduras' where name = 'champiñon 1/4';
update public.products set category = 'verduras' where name = 'Champiñones picados';
update public.products set category = 'verduras' where name = 'Chapsui de verduras';
update public.products set category = 'verduras' where name = 'Choclo americano Unidad';
update public.products set category = 'verduras' where name = 'Choclo Grande';
update public.products set category = 'verduras' where name = 'Coliflor Unidad';
update public.products set category = 'verduras' where name = 'Dientes de dragón';
update public.products set category = 'verduras' where name = 'Espinacas Kg';
update public.products set category = 'verduras' where name = 'Lechuga Costina';
update public.products set category = 'verduras' where name = 'Lechuga Escarola Unidad';
update public.products set category = 'verduras' where name = 'Lechuga Milanesa Unidad';
update public.products set category = 'verduras' where name = 'Lechugas Española Unidad';
update public.products set category = 'verduras' where name = 'Lechugas Marina Unidad';
update public.products set category = 'verduras' where name = 'Limones Kg';
update public.products set category = 'verduras' where name = 'Mata de Acelga';
update public.products set category = 'verduras' where name = 'Mata de apio Unidad';
update public.products set category = 'verduras' where name = 'Mongoliana (Dientes de dragon, Cebollín, Pimentón y Champiñon)';
update public.products set category = 'verduras' where name = 'Papas Kg';
update public.products set category = 'verduras' where name = 'Pepinos Unidad';
update public.products set category = 'verduras' where name = 'Pimentón amarillo Unidad';
update public.products set category = 'verduras' where name = 'Pimentón rojo Unidad';
update public.products set category = 'verduras' where name = 'Pimentón verde Unidad';
update public.products set category = 'verduras' where name = 'Porotos Granados Kg';
update public.products set category = 'verduras' where name = 'Porotos verdes Kg';
update public.products set category = 'verduras' where name = 'Porotos verdes picados (bandeja con 200grs. Aprox.)';
update public.products set category = 'verduras' where name = 'Repollo Unidad';
update public.products set category = 'verduras' where name = 'Tomates Cherry 1/4 Kg';
update public.products set category = 'verduras' where name = 'Tomates Kg';
update public.products set category = 'verduras' where name = 'Zanahorias Kg';
update public.products set category = 'verduras' where name = 'Zapallo Camote 1/2';
update public.products set category = 'verduras' where name = 'Zapallos italianos Unidad';
update public.products set category = 'hierbas y complementos' where name = 'Ají verde Unidad';
update public.products set category = 'hierbas y complementos' where name = 'Albahaca Mata';
update public.products set category = 'hierbas y complementos' where name = 'Cebollín 3 unidades';
update public.products set category = 'hierbas y complementos' where name = 'Ciboulette';
update public.products set category = 'hierbas y complementos' where name = 'Cilantro';
update public.products set category = 'hierbas y complementos' where name = 'Perejil';
update public.products set category = 'legumbres y otros' where name = 'Aceitunas (1/2 Kilo)';
update public.products set category = 'legumbres y otros' where name = 'Alemendras Confitadas 100 grs.';
update public.products set category = 'legumbres y otros' where name = 'Almendras 500grs.';
update public.products set category = 'legumbres y otros' where name = 'Cebolla en escabeche 500 grs.';
update public.products set category = 'legumbres y otros' where name = 'Garbanzos Kg';
update public.products set category = 'legumbres y otros' where name = 'Genjibre (100 grs.)';
update public.products set category = 'legumbres y otros' where name = 'Huevos de color extra (Unidad)';
update public.products set category = 'legumbres y otros' where name = 'Huevos de color super extra (c/u)';
update public.products set category = 'legumbres y otros' where name = 'Huevos Jumbo (Unidad)';
update public.products set category = 'legumbres y otros' where name = 'Lentejas Kg';
update public.products set category = 'legumbres y otros' where name = 'Locos Cocidos (2 a 3 unidades)';
update public.products set category = 'legumbres y otros' where name = 'Longanizas Ahumadas (Al vacío Kg)';
update public.products set category = 'legumbres y otros' where name = 'Maní Confitado 250 grs.';
update public.products set category = 'legumbres y otros' where name = 'Maní Tostado 250 grs.';
update public.products set category = 'legumbres y otros' where name = 'Mermeladas 420 grs. Hermanas de Quilvo 100% caseras. 2*11.000';
update public.products set category = 'legumbres y otros' where name = 'Nueces 500 grs.';
update public.products set category = 'legumbres y otros' where name = 'Poroto Burro Kg';
update public.products set category = 'legumbres y otros' where name = 'Poroto Payar Kg';
update public.products set category = 'legumbres y otros' where name = 'Poroto Pelado Kg';
update public.products set category = 'legumbres y otros' where name = 'Pulpa de Tomate 370 grs. Hermanas de Quilvo 100% caseras. 2*6000';
